# Cloud Build configuration for backend deployment
# This template is parameterized and reusable across projects
#
# Usage:
#   - Copy this file to your project root as cloudbuild.backend.yaml
#   - Customize substitutions and build steps for your project
#   - Secrets are managed via Google Secret Manager
#
# Substitutions (set via trigger or command line):
#   _SERVICE_NAME: Backend service name (e.g., "my-api")
#   _REGION: GCP region (e.g., "us-central1")
#   _ENV: Environment (prod)
#   _DOCKERFILE_PATH: Path to Dockerfile (default: "apps/api/Dockerfile" or "packages/backend/Dockerfile")

substitutions:
  _SERVICE_NAME: "backend-service"
  _REGION: "us-central1"
  _ENV: "prod"
  _DOCKERFILE_PATH: "apps/api/Dockerfile"
  _BUILD_CONTEXT: "."
  # Note: Use $BUILD_ID instead of $SHORT_SHA for manual builds
  # $SHORT_SHA is only available in git-triggered builds

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  # Note: timeout removed - not supported in options, use default (10 minutes)

steps:
  # Optional: Run database migrations before deployment
  # Uncomment and customize if your project uses database migrations
  # - name: 'node:20-alpine'
  #   entrypoint: 'sh'
  #   args:
  #     - '-c'
  #     - |
  #       # Install dependencies
  #       npm install --frozen-lockfile
  #
  #       # Run migrations
  #       npm run db:migrate
  #   secretEnv: ['DATABASE_URL']

  # Optional: Run tests before building
  # Uncomment and customize for your test setup
  # - name: 'node:20-alpine'
  #   entrypoint: 'sh'
  #   args:
  #     - '-c'
  #     - |
  #       npm install --frozen-lockfile
  #       npm run test
  #   id: 'run-tests'

  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    env:
      - "DOCKER_BUILDKIT=1"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:$BUILD_ID"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:latest"
      - "-f"
      - "${_DOCKERFILE_PATH}"
      - "${_BUILD_CONTEXT}"
    id: "build-image"

  # Push image with commit SHA tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:$BUILD_ID"
    id: "push-image-sha"

  # Push latest tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:latest"
    id: "push-image-latest"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:$BUILD_ID"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "cloud-run-sa@$PROJECT_ID.iam.gserviceaccount.com"
      # Resource configuration (adjust based on your needs)
      - "--memory"
      - "1Gi"
      - "--cpu"
      - "1"
      - "--timeout"
      - "300"
      # Scaling configuration
      - "--min-instances"
      - "1"
      - "--max-instances"
      - "100"
      # Environment variables (non-sensitive)
      # Note: PORT is automatically set by Cloud Run, don't set it manually
      - "--set-env-vars"
      - "NODE_ENV=production,ENV=${_ENV},LOG_LEVEL=info"
      # Secrets from Secret Manager (customize with your secret names)
      # Format: SECRET_ENV_VAR=secret-name:version
      - "--update-secrets"
      - "DATABASE_URL=database-url:latest,API_KEY=api-key:latest"
    id: "deploy-cloud-run"

# Images to be pushed to Artifact Registry
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:$BUILD_ID"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:latest"

# Secrets accessible during build (if needed for migrations/tests)
# Uncomment if you need secrets during build steps
# availableSecrets:
#   secretManager:
#     - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
#       env: 'DATABASE_URL'

tags:
  - "backend"
  - "${_ENV}"
  - "cloud-run"
