# Cloud Build configuration for frontend deployment
# This template is parameterized and reusable across projects
#
# Usage:
#   - Copy this file to your project root as cloudbuild.frontend.yaml
#   - Customize substitutions and build steps for your project
#   - Build-time environment variables are passed as Docker build args
#
# Substitutions (set via trigger or command line):
#   _SERVICE_NAME: Frontend service name (e.g., "my-app")
#   _REGION: GCP region (e.g., "us-central1")
#   _ENV: Environment (prod)
#   _DOCKERFILE_PATH: Path to Dockerfile (default: "apps/web/Dockerfile" or "packages/frontend/Dockerfile")
#   _BUILD_CONTEXT: Build context directory (default: ".")

substitutions:
  _SERVICE_NAME: "frontend-service"
  _REGION: "us-central1"
  _ENV: "prod"
  _DOCKERFILE_PATH: "apps/web/Dockerfile"
  _BUILD_CONTEXT: "."
  # Note: Use $BUILD_ID instead of $SHORT_SHA for manual builds
  # $SHORT_SHA is only available in git-triggered builds

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  # Note: timeout removed - not supported in options, use default (10 minutes)

steps:
  # Optional: Run frontend tests before building
  # Uncomment and customize for your test setup
  # - name: 'node:20-alpine'
  #   entrypoint: 'sh'
  #   args:
  #     - '-c'
  #     - |
  #       npm install --frozen-lockfile
  #       npm run test
  #   id: 'run-tests'

  # Build the Docker image with build-time environment variables
  # These are embedded at build time (safe for public values)
  - name: "gcr.io/cloud-builders/docker"
    env:
      - "DOCKER_BUILDKIT=1"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:$BUILD_ID"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:latest"
      # Build arguments for frontend environment variables
      # These are public values that get embedded in the build
      - "--build-arg"
      - "NEXT_PUBLIC_API_URL=https://api.example.com"
      - "--build-arg"
      - "NEXT_PUBLIC_ENV=${_ENV}"
      # Add more build args as needed for your frontend
      # - '--build-arg'
      # - 'NEXT_PUBLIC_ANALYTICS_ID=your-analytics-id'
      - "-f"
      - "${_DOCKERFILE_PATH}"
      - "${_BUILD_CONTEXT}"
    id: "build-image"

  # Push image with commit SHA tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:$BUILD_ID"
    id: "push-image-sha"

  # Push latest tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:latest"
    id: "push-image-latest"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:$BUILD_ID"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "cloud-run-sa@$PROJECT_ID.iam.gserviceaccount.com"
      # Resource configuration (frontend typically needs less resources)
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--timeout"
      - "60"
      # Scaling configuration
      - "--min-instances"
      - "1"
      - "--max-instances"
      - "50"
      # Concurrency (how many requests per instance)
      - "--concurrency"
      - "80"
      # Environment variables (runtime, not build-time)
      - "--set-env-vars"
      - "NODE_ENV=production,ENV=${_ENV}"
    id: "deploy-cloud-run"

# Images to be pushed to Artifact Registry
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:$BUILD_ID"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/docker-repo/${_SERVICE_NAME}:latest"

tags:
  - "frontend"
  - "${_ENV}"
  - "cloud-run"
# Notes:
# - Build-time variables (--build-arg) are embedded in the image
# - Use build args only for public, non-sensitive values
# - Never use build args for secrets or API keys
# - Runtime environment variables (--set-env-vars) can be changed without rebuilding

